name: "Terraform-Plan-Infra-Plan"

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:	
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETE_ID }}
      AWS_REGION: 'us-west-1'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init
        # env:
        #   TF_WORKSPACE: sandbox        

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: cd modules && cd vpc && terraform init && terraform plan -no-color
      # - name: Terraform plan for sandbox
      #   id: plan for sandbox
      #   if: github.event_name == 'push'
      #   run: cd environments && cd sandbox && terraform init && terraform plan -no-color
      # - name: Terraform plan for prod
      #   id: plan for prod
      #   if: github.event_name == 'push'
      #   run: cd environments && cd production && terraform init && terraform plan -no-color        